### ISSUE TITLE
Not finding the username or password xpath

### ISSUE THREAD

**Issue by alexhaislip** [nickmatthews713/instagram_automation_tool#1]
Here is the terminal output: 

`Traceback (most recent call last):
  File "automation.py", line 81, in <module>
    main()
  File "automation.py", line 56, in main
    login(driver)
  File "/Users/alexanderhaislip/Desktop/instagram_automation_tool/util.py", line 20, in login
    '//*[@id="react-root"]/section/main/div/article/div/div[1]/div/form/div[2]/'
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//*[@id="react-root"]/section/main/div/article/div/div[1]/div/form/div[2]/div/label/input"}
  (Session info: chrome=85.0.4183.121)
  (Driver info: chromedriver=2.42.591059 (a3d9684d10d61aa0c45f6723b327283be1ebaad8),platform=Mac OS X 10.15.6 x86_64)`

**Comment by alexhaislip** [comment]
Closing the issue
